import type { Topic } from "@/types";

export const topics: Topic[] = [
  {
    slug: "box-folding",
    icon: "📦",
    title: "Box Folding",
    description: "Visualize how 2D nets fold into 3D shapes.",
    category: "spatial",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/box.png",
    coverImageDark: "/images/icons/SkyQuests/box dark.png",
  },
  {
    slug: "box-unfolding",
    icon: "📦",
    title: "Box Unfolding",
    description: "Rotate a folded cube and find the flat net that unfolds from it.",
    category: "spatial",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/unbox.png",
    coverImageDark: "/images/icons/SkyQuests/unbox dark.png",
  },
  {
    slug: "missing-cube",
    icon: "🧊",
    title: "Missing Cube",
    description: "Find the 3D piece that completes an incomplete cube.",
    category: "spatial",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/rubik.png",
    coverImageDark: "/images/icons/SkyQuests/rubik dark.png",
  },
  {
    slug: "jigsaw",
    icon: "🧩",
    title: "Jigsaw",
    description: "Mentally assemble loose shape parts and choose the completed silhouette.",
    category: "spatial",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/jigsaw.png",
    coverImageDark: "/images/icons/SkyQuests/jigsaw dark.png",
  },
  {
    slug: "find-similar-shape",
    icon: "🔷",
    title: "Find Similar Shape",
    description: "Find the answer choice that exactly matches the target shape.",
    category: "scanning",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/similar.png",
    coverImageDark: "/images/icons/SkyQuests/similar dark.png",
  },
  {
    slug: "number-series",
    icon: "🔢",
    title: "Number Series",
    description: "Find the pattern in numerical sequences.",
    category: "logical",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/number.png",
    coverImageDark: "/images/icons/SkyQuests/number dark.png",
    coverBg: "bg-white dark:bg-white/5",
  },
  {
    slug: "calculate",
    icon: "🧮",
    title: "Calculate",
    description: "Practice arithmetic and mental math.",
    category: "approximation",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/calculate.png",
    coverImageDark: "/images/icons/SkyQuests/calculate dark.png",
  },
  {
    slug: "approximation",
    icon: "≈",
    title: "Approximation",
    description: "Estimate answers across arithmetic, units, geometry, physics, finance, and time questions.",
    category: "approximation",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/approx.png",
    coverImageDark: "/images/icons/SkyQuests/approx dark.png",
  },
  {
    slug: "missing-operator",
    icon: "🧮",
    title: "Missing Operator",
    description: "Practice arithmetic and mental math.",
    category: "approximation",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/cal.png",
    coverImageDark: "/images/icons/SkyQuests/cal dark.png",
  },
  {
    slug: "dern-jood",
    icon: "🎵",
    title: "Dern-Jood PRO MAX",
    description: "Answer mental math questions while tracking rhythm, time pressure, and input mode.",
    category: "multitasking",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/DJ.png",
    coverImageDark: "/images/icons/SkyQuests/DJ dark.png",
  },
  {
    slug: "joy-stick-game",
    icon: "🕹️",
    title: "Joy-Stick Game",
    description: "Control a top-view aircraft marker, capture color targets, avoid moving obstacles, and answer math questions.",
    category: "multitasking",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/joy.png",
    coverImageDark: "/images/icons/SkyQuests/joy dark.png",
  },
  {
    slug: "multitasking-assessment",
    icon: "▦",
    title: "Multitasking Assessment",
    description: "Run a cockpit-style multitasking battery with monitoring, tracking, communications, and resource control.",
    category: "multitasking",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/joy.png",
    coverImageDark: "/images/icons/SkyQuests/joy dark.png",
  },
  {
    slug: "aircraft-rotation",
    icon: "✈️",
    title: "Aircraft Rotation",
    description: "Calculate aircraft heading changes and visualize rotations.",
    category: "spatial",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/aircraft rota.png",
    coverImageDark: "/images/icons/SkyQuests/aircaft rota dark.png",
  },
  {
    slug: "string-comparison",
    icon: "👁️",
    title: "String Comparison",
    description: "Quickly compare alphanumeric strings and identify differences.",
    category: "scanning",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/string.png",
    coverImageDark: "/images/icons/SkyQuests/string dark.png",
  },
  {
    slug: "string-sprint",
    icon: "⚡",
    title: "String Sprint",
    description: "Make rapid same-or-different calls on string pairs under a tight clock.",
    category: "scanning",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/sprint.png",
    coverImageDark: "/images/icons/SkyQuests/sprint dark.png",
  },
  {
    slug: "scanning-shape",
    icon: "🔷",
    title: "Scanning Shape",
    description: "Identify hidden letters in shape displays across 8 timed visual scanning sections.",
    category: "scanning",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/shape.png",
    coverImageDark: "/images/icons/SkyQuests/shape dark.png",
  },
  {
    slug: "short-term-memory",
    icon: "🧠",
    title: "Short-Term Memory Table",
    description: "Memorize a grid of mixed symbols, then recreate it from memory.",
    category: "short-term-memory",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/STM table.png",
    coverImageDark: "/images/icons/SkyQuests/STM table dark.png",
  },
  {
    slug: "passage-recall",
    icon: "🧠",
    title: "Passage Recall",
    description: "Read an aviation passage, hold the details in memory, then answer recall questions after it disappears.",
    category: "short-term-memory",
    isLocked: false,
    coverImage: "/images/icons/SkyQuests/STM PS.png",
    coverImageDark: "/images/icons/SkyQuests/STM PS dark.png",
  },
];

export const topicSlugs = new Set(topics.map((t) => t.slug));
